first version of task m
MaximOkleev/informatics pull request #1
Opened 2022-09-16 16:14 UTC by MaximOkleev

2022-09-19 13:18 UTC, justas05 requested changes

2022-09-19 13:18 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +	scanf("%d", &n);
add empty line after definitions
```suggestion
	
	scanf("%d", &n);
```

2022-09-19 13:18 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +	int b = 0;
What does it mean b? or c?
Give the meaningful names for variables.

2022-09-19 13:18 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +	printf("%d",c);
add space after comma

2022-09-19 13:18 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +		if(b == 0) c++;
```suggestion
		if(b == 0)
		{
		    c++;
		}
```

2022-09-19 13:26 UTC, MaximOkleev commented on learning_a_programming_language/loop_operator/m.c
> +	printf("%d",c);
What is it comma?

2022-09-21 05:37 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +	int schit = 0;
schit? What does it mean?

2022-09-21 05:37 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +		if(schit == 0)
Space after if

2022-09-21 05:37 UTC, justas05 commented on learning_a_programming_language/loop_operator/m.c
> +	printf("%d",count_zero);
Space after comma

2022-10-14 17:55 UTC, justas05 approved these changes

2022-10-14 18:08 UTC, merged